# Generated by Django 5.0.6 on 2024-06-28 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30)),
                ('id_modelo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('extension', models.CharField(max_length=5)),
                ('tipo', models.CharField(max_length=20)),
                ('subtipo', models.CharField(max_length=20)),
                ('ruta', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=8)),
                ('tamanio', models.CharField(max_length=10)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'db_table': 'tmarch10',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('nivel', models.CharField(max_length=50)),
                ('duracion', models.CharField(blank=True, max_length=50, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desc', models.TextField(blank=True)),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'tmcur10',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('dia_reunion', models.CharField(max_length=100)),
                ('horario_reunion', models.TimeField()),
                ('estado', models.CharField(max_length=8)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ministerio',
                'verbose_name_plural': 'Ministerios',
                'db_table': 'tbminis',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(max_length=8)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'TipoDocumento',
                'verbose_name_plural': 'TipoDocumentos',
                'db_table': 'tbtipodoc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(max_length=8)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'TipoPersona',
                'verbose_name_plural': 'TipoPersonas',
                'db_table': 'tbtipoper',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nombre_completo', models.CharField(blank=True, max_length=200)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_conversion', models.DateField(blank=True, null=True)),
                ('fecha_bautismo', models.DateField(blank=True, null=True)),
                ('celular', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=80)),
                ('estado', models.CharField(max_length=8)),
                ('ruta_carpeta', models.CharField(blank=True, max_length=250, null=True)),
                ('desc', models.TextField(blank=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('ministerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.ministerio')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.tipodocumento')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'tmper10',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CursoPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.curso')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.persona')),
            ],
            options={
                'verbose_name': 'CursoPersona',
                'verbose_name_plural': 'CursoPersonas',
                'db_table': 'tmper30',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonaTipoPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.persona')),
                ('tipo_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.tipopersona')),
            ],
            options={
                'verbose_name': 'PersonaTipoPersona',
                'verbose_name_plural': 'PersonaTipoPersonas',
                'db_table': 'tmper20',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(max_length=8)),
                ('desc', models.TextField(blank=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.persona')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'tmusu10',
                'managed': True,
            },
        ),
    ]
