# Generated by Django 5.0.6 on 2024-07-16 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaPareja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nombre_completo', models.CharField(blank=True, max_length=200)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('celular', models.CharField(max_length=15)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(max_length=8)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'PersonaPareja',
                'verbose_name_plural': 'PersonaParejas',
                'db_table': 'tmpar10',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pareja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=8)),
                ('desc', models.TextField(blank=True, null=True)),
                ('idonea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parejas_idonea', to='registro.personapareja')),
                ('idoneo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parejas_idoneo', to='registro.personapareja')),
            ],
            options={
                'verbose_name': 'Pareja',
                'verbose_name_plural': 'Parejas',
                'db_table': 'tmpar20',
                'managed': True,
            },
        ),
    ]
