# Generated by Django 5.0.6 on 2024-07-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_personapareja_pareja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wsp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('palabra_clave', models.CharField(blank=True, max_length=50, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Wsp',
                'verbose_name_plural': 'Wsps',
                'db_table': 'tbwsp',
                'managed': True,
            },
        ),
    ]
